In [2]:
import numpy as np
import pandas as pd

In [3]:
lista = pd.read_csv('C:/Users/F3880346/Downloads/amostra_exercicio.csv', sep=',', header=None)
matriz = np.array(lista)
matriz = matriz.reshape(10,10)
print('Essa é uma matriz bidimensional 10x10 com números aleatórios: \n', matriz)

Essa é uma matriz bidimensional 10x10 com números aleatórios: 
 [[58 97 48 36 88 23 73 54 32 37]
 [79 43 54 55 78 84 82 64 73 61]
 [55 79 71  6 62 85 25 85 31 60]
 [29  6 64 11 43 41 46 19 89 55]
 [73 56 11 72 68 86 70 31 61 26]
 [64 70 90  3 22 20  5 65 39 89]
 [79 13 47 25 43 71 33 75 25 64]
 [88 24 30 34  4 84 81 39 83 24]
 [81 43 93 49 74 92 35 20 54 31]
 [40 76 94 58 64 78  6 13 72 56]]


In [4]:
#Obter dados estatísticos (pelo menos 3, uma com axis=1, a outra com axis = 0 e a última sem axis);
valor_media= matriz.mean()
valor_desvio_padrao = matriz.std()
valor_medio_eixo0 = np.mean(matriz, axis=0)
valor_medio_eixo1 = np.mean(matriz, axis=1)
print ('Desvio padrão', valor_desvio_padrao, '\nMédia calculada:', valor_media)
print ('Valor médio no eixo 0', valor_medio_eixo0, '\nValor médio no eixo 1', valor_medio_eixo1)

Desvio padrão 25.901526982014015 
Média calculada: 52.97
Valor médio no eixo 0 [64.6 50.7 60.2 34.9 54.6 66.4 45.6 46.5 55.9 50.3] 
Valor médio no eixo 1 [54.6 67.3 55.9 40.3 55.4 46.7 47.5 49.1 57.2 55.7]


In [5]:
#Obter a transposta da matriz e realizar uma operação com ela
matriz_transposta = matriz.T
matriz_transposta = matriz_transposta * 1.5
print(matriz_transposta)

[[ 87.  118.5  82.5  43.5 109.5  96.  118.5 132.  121.5  60. ]
 [145.5  64.5 118.5   9.   84.  105.   19.5  36.   64.5 114. ]
 [ 72.   81.  106.5  96.   16.5 135.   70.5  45.  139.5 141. ]
 [ 54.   82.5   9.   16.5 108.    4.5  37.5  51.   73.5  87. ]
 [132.  117.   93.   64.5 102.   33.   64.5   6.  111.   96. ]
 [ 34.5 126.  127.5  61.5 129.   30.  106.5 126.  138.  117. ]
 [109.5 123.   37.5  69.  105.    7.5  49.5 121.5  52.5   9. ]
 [ 81.   96.  127.5  28.5  46.5  97.5 112.5  58.5  30.   19.5]
 [ 48.  109.5  46.5 133.5  91.5  58.5  37.5 124.5  81.  108. ]
 [ 55.5  91.5  90.   82.5  39.  133.5  96.   36.   46.5  84. ]]


In [13]:
#Realizar um produto escalar entre duas matrizes ou de um array com uma matriz
matriz_resultado = matriz * matriz_transposta
print(matriz_resultado)

[[ 5046.  14113.5  3456.   1944.  11616.    793.5  7993.5  4374.   1536.
   2053.5]
 [ 6873.   6256.5  3888.   2970.  10296.   2898.   8979.   5184.   3504.
   3385.5]
 [ 4785.  11494.5  5112.    324.   8184.   2932.5  2737.5  6885.   1488.
   3330. ]
 [ 2523.    873.   4608.    594.   5676.   1414.5  5037.   1539.   4272.
   3052.5]
 [ 6351.   8148.    792.   3888.   8976.   2967.   7665.   2511.   2928.
   1443. ]
 [ 5568.  10185.   6480.    162.   2904.    690.    547.5  5265.   1872.
   4939.5]
 [ 6873.   1891.5  3384.   1350.   5676.   2449.5  3613.5  6075.   1200.
   3552. ]
 [ 7656.   3492.   2160.   1836.    528.   2898.   8869.5  3159.   3984.
   1332. ]
 [ 7047.   6256.5  6696.   2646.   9768.   3174.   3832.5  1620.   2592.
   1720.5]
 [ 3480.  11058.   6768.   3132.   8448.   2691.    657.   1053.   3456.
   3108. ]]


In [15]:
#Criar um filtro para a sua matriz
matriz_filtrada = matriz[matriz < 50]
print('A matriz para o filtro das dezenas inferiores a 50 é \n', matriz_filtrada )

A matriz para o filtro das dezenas inferiores a 50 é 
 [48 36 23 32 37 43  6 25 31 29  6 11 43 41 46 19 11 31 26  3 22 20  5 39
 13 47 25 43 33 25 24 30 34  4 39 24 43 49 35 20 31 40  6 13]


In [16]:
#Realizar alguma operação aritmética (número com matriz, array com matriz, etc.)
matriz_filtrada += 10
print('Resultado da matriz filtrada acrescido de 10 \n', matriz_filtrada)
matriz_filtrada *= 2
print('Resultado da matriz filtrada multiplicado por 2 \n', matriz_filtrada)

Resultado da matriz filtrada acrescido de 10 
 [58 46 33 42 47 53 16 35 41 39 16 21 53 51 56 29 21 41 36 13 32 30 15 49
 23 57 35 53 43 35 34 40 44 14 49 34 53 59 45 30 41 50 16 23]
Resultado da matriz filtrada dividido por 2 
 [116  92  66  84  94 106  32  70  82  78  32  42 106 102 112  58  42  82
  72  26  64  60  30  98  46 114  70 106  86  70  68  80  88  28  98  68
 106 118  90  60  82 100  32  46]
